### ISSUE TITLE
WiFi M.2 card

### ISSUE THREAD

**Issue by phodina** [esp32-open-mac/esp32-open-mac#11]
Hi,
thanks for really cool reverse-engineering project. Been looking for a wireless card with open firmware.

Since I found this project I made a simple M.2 key E card with ESP32 C6.

Need to verify the design and fabricate it to run the code there.

Any ideas are welcome!

https://gitlab.com/phodina/librewifi

**Comment by redfast00** [comment]
Very cool project, but I have some remarks for your plan to 'Attempt to switch to the open source implementation'

- currently, only the plain ESP32 has been tested, not any variants like the ESP32-C6. It's very unlikely that the C6 will work out of the box with this code.
- this codebase is extremely work in progress; we can send/receive packets and have a very basic implementation that can connect to an access point, but this is nowhere near ready; SDIO is not even on the roadmap at the moment

I still wish you good luck with your project, it looks interesting :)

**Comment by phodina** [comment]
Understood @redfast00 . Thanks

- Do you think using plain ESP32 might be better for know? I'm not pedantic about the RISC-V variant, just there's the ditch of Tensillica ISA dependency.

- I'm not saying it will work by just flashing the code, however, having a hardware platform that you can interact from Linux and debug easily is a nice first step (Then again it can be done on board from Aliexpress with some wires but it lacks the polishing of using it in laptop).

**Comment by Frostie314159** [comment]
The thing for us is, that the esp32 is the most used one. This means that we've got more people, that would potentially get on board. However the C6 is an interesting target, with its WiFi, BT and IEEE 802.15.4 support. If you want to reverse it, I'd wait for the C5, since a wifi nic without 5ghz support wouldn't be used by anyone.

**Comment by phodina** [comment]
Good the point. The C6 is interesting but the idea is to use a whole module due to FCC so there's no need to certify the radio. Therefore I can make also a M.2 module with ESP32 to target wider audience.

**Comment by phodina** [comment]
@Frostie314159 https://gitlab.com/phodina/librewifi#esp32

Found time to design another board with ESP32. Will send both gerbers to fab.
