### ISSUE TITLE
Linker error while building on ESP-IDF 5.3.1

### ISSUE THREAD

**Issue by likhin-maroli** [esp32-open-mac/esp32-open-mac#16]
Getting the following undefined reference error  while building on esp-idf-5.3.1 
"E:/Espressif/frameworks/esp-idf-v5.3.1/myapps/esp32-open-mac-main/main/hwinit.c:145:(.text.wifi_hw_start_openmac+0x15): undefined reference to `ic_enable'
collect2.exe: error: ld returned 1 exit status"

**Comment by redfast00** [comment]
https://github.com/esp32-open-mac/esp32-open-mac/blob/ec875374626e6a64a448f8ecf1fc729c9d6a2641/main/main.c#L18

Did you remove this line? Only 5.0.1 is supported at the moment.

**Comment by likhin-maroli** [comment]
Yes I did. Then I forgott about it. And posted the issue here. Sorry for that.
