### ISSUE TITLE
Faulty if statement in mac.c

### ISSUE THREAD

**Issue by BrendanMesters** [esp32-open-mac/esp32-open-mac#4]
The if statement to "check that receiver mac address matcher our mac address OR is broadcast" uses an and statement (lines 58-59 in main/mac.c)

**Comment by jacmet** [comment]
I think you are getting confused about the fact that memcmp() returns 0 on equal, and in boolean algebra `!A && !B == A || B`

**Comment by BrendanMesters** [comment]
you're absolutely right, my bad
