### ISSUE TITLE
Document hardcoded values

### ISSUE THREAD

**Issue by Lionade** [esp32-open-mac/esp32-open-mac#6]
Thanks for the greate work and effort guys!

I am currently trying to setup the project using your last master branch and an ESP32-WROOM-32 board. I created a simple/plain 802.11g AP using hostapd and I am trying to connect to it by changing the receiver and bssid MAC addresses in the raw 802.11 frames like so:

```
static uint8_t to_ap_auth_frame[] = {
    0xb0, 0x00, 0x00, 0x00,
    0xec, 0x08, 0x6b, 0x18, 0xba, 0x20, // addr of AP
    0x00, 0x23, 0x45, 0x67, 0x89, 0xab, // transmitter addr.
    0xec, 0x08, 0x6b, 0x18, 0xba, 0x20, // addr of AP(bssid).
    0x00, 0x00, // sequence control.
    0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0, 0, 0, 0 /*FCS*/};
```

Hostapd reports receiving Authentication Request but the Authentication Responds apparently is not acknowledged as logged by hostapd:
`STA 00:23:45:67:89:ab IEEE 802.11: did not acknowledge authentication response`

Is there maybe something else that needs adjustment beside the MAC addr that I missed? 
Sorry if this is a trivial question but I tried many different things without any success.

**Comment by redfast00** [comment]
Yes, the MAC address, and SSID (this is implemented on the https://github.com/esp32-open-mac/esp32-open-mac/commits/implement-init/ branch); this also only works on channel 1, with open authentication

**Comment by redfast00** [comment]
See https://github.com/esp32-open-mac/esp32-open-mac/blob/implement-init/main/mac.c#L28; edit ssid and ap_address

**Comment by Lionade** [comment]
Switching to channel 1 did the trick, thank you! Maybe it is worth mentioning somewhere what values are still hardcoded and where to find them, for anyone trying to test your code.

**Comment by redfast00** [comment]
We eliminated most of the hardcoded values, only the ssid is hardcoded for now, with scanning working across all 12 channels
